BibliotecaCacau/Controllers/ClienteController.cs
using BibliotecaBookHub.Models.Contracts.Services;
using BibliotecaBookHub.Models.DTO;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BibliotecaBookHub.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteService _clienteService;

        public ClienteController(IClienteService clienteService)
        {
            _clienteService = clienteService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            try
            {
                var clientes = _clienteService.Listar();
                return View(clientes);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Nome, Cpf, Email, Fone")] ClienteDTO cliente)
        {
            try
            {
                _clienteService.Cadastrar(cliente);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult Edit(string? id)
        {
            if(string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var cliente = _clienteService.PesquisarPorId(id);
            if(cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("Id, Nome, Cpf, Email, Fone")] ClienteDTO cliente)
        {
            if(string.IsNullOrEmpty(cliente.Id))
            {
                NotFound();
            }

            try 
            {
                _clienteService.Atualizar(cliente);
                return RedirectToAction("List");
            } 
            catch(Exception ex) 
            {
                throw ex;
            }
        }

        public IActionResult Details(string? id)
        {
            if(string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var livro = _clienteService.PesquisarPorId(id);
            if(livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        public IActionResult Delete(string? id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var cliente = _clienteService.PesquisarPorId(id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind("Id, Nome, Cpf, Email, Fone")] ClienteDTO cliente)
        {
            try
            {
                _clienteService.Deletar(cliente.Id);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

BibliotecaCacau/Controllers/EmprestimoController.cs
using BibliotecaBookHub.Models.Contracts.Services;
using BibliotecaBookHub.Models.DTO;
using BibliotecaCacau.Models.DTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BibliotecaBookHub.Controllers
{
    public class EmprestimoController : Controller
    {
        private readonly IEmprestimoLivroService _emprestimoService;
        private readonly IClienteService _clienteService;
        private readonly ILivroService _livroService;

        public EmprestimoController(IEmprestimoLivroService emprestimoService,
            IClienteService clienteService,
            ILivroService livroService)
        {
            _emprestimoService = emprestimoService;
            _clienteService = clienteService;
            _livroService = livroService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Consulta()
        {
            return View();
        }

        public IActionResult PesquisarEmprestimo(string nomeLivro, string nomeCliente, string dataEmprestimo)
        {
            DateTime dataEmprestimoFormatada = DateTime.Parse(dataEmprestimo);
            try
            {
                ConsultaEmprestimoDTO result = _emprestimoService.PesquisarEmprestimo(nomeLivro, nomeCliente, dataEmprestimoFormatada);
                return View(result);
            } 
            catch(Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EfetuarEmprestimo([Bind("Cliente, Livro")] EmprestimoDTO emprestimo)
        {
            try
            {
                int userId = Int32.Parse(HttpContext.Session.GetString("_UserId"));
                string login = HttpContext.Session.GetString("_Login");

                EmprestimoLivroDTO entidade = new EmprestimoLivroDTO();
                entidade.Cliente = PesquisarCliente(emprestimo.Cliente);
                entidade.ClienteId = entidade.Cliente.Id;

                entidade.Livro = PesquisarLivro(emprestimo.Livro);
                entidade.LivroId = entidade.Livro.Id;

                entidade.UsuarioId = userId;
                entidade.Usuario = new UsuarioDTO { Id = userId, Login = login };

                _emprestimoService.EfetuarEmprestimo(entidade);

                return RedirectToAction("Consulta");
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult EfetuarDevolucao(int emprestimoId, string livroId)
        {
            try
            {
                _emprestimoService.EfetuarDevolucao(emprestimoId, livroId);
                return RedirectToAction("Consulta");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ClienteDTO PesquisarCliente(string nome)
        {
            var cliente = _clienteService.Listar()
                .Where(p => p.Nome
                .Equals(nome))
                .FirstOrDefault();

            return cliente;
        }

        public LivroDTO PesquisarLivro(string nome)
        {
            var livro = _livroService.Listar()
                .Where(p => p.Nome
                .Equals(nome))
                .FirstOrDefault();

            return livro;
        }

        public LivroDTO PesquisarUsuario(string nome)
        {
            var livro = _livroService.Listar()
                .Where(p => p.Nome
                .Equals(nome))
                .FirstOrDefault();

            return livro;
        }

        public IActionResult PesquisarClientes(string term)
        {
            var clientes = _clienteService.Listar();
            var clientesAtivos = clientes.Where(p => p.StatusClienteId.Equals("1")).ToList();
            var listaNomeClientes = clientesAtivos.Select(p => p.Nome).ToList();
            var filtro = listaNomeClientes.Where(p => p.Contains(term, StringComparison.CurrentCultureIgnoreCase)).ToList();
            return Json(filtro);
        }

        public IActionResult PesquisarLivros(string term)
        {
            var livros = _livroService.Listar();
            var livrosDisponiveis = livros.Where(p => p.StatusLivroId == 1).ToList();
            var listaLivros = livrosDisponiveis.Select(p => p.Nome).ToList();
            var filtro = listaLivros.Where(p => p.Contains(term, StringComparison.CurrentCultureIgnoreCase)).ToList();
            return Json(filtro);
        }
    }
}

BibliotecaCacau/Controllers/LivroController.cs
using BibliotecaBookHub.Models.Contracts.Services;
using BibliotecaBookHub.Models.DTO;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace BibliotecaBookHub.Controllers
{
    public class LivroController : Controller
    {
        private readonly ILivroService _livroService;

        public LivroController(ILivroService livroService)
        {
            _livroService = livroService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Nome, Autor, Editora")] LivroDTO livro)
        {
            try
            {
                _livroService.Cadastrar(livro);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult Edit(string? id)
        {
            if(string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var livro = _livroService.PesquisarPorId(id);
            if(livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("Id, Nome, Autor, Editora")] LivroDTO livro)
        {
            if(string.IsNullOrEmpty(livro.Id))
            {
                NotFound();
            }

            try 
            {
                _livroService.Atualizar(livro);
                return RedirectToAction("List");
            } 
            catch(Exception ex) 
            {
                throw ex;
            }
        }

        public IActionResult Details(string? id)
        {
            if(string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var livro = _livroService.PesquisarPorId(id);
            if(livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        public IActionResult Delete(string? id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var livro = _livroService.PesquisarPorId(id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind("Id, Nome, Autor, Editora")] LivroDTO livro)
        {
            try
            {
                _livroService.Deletar(livro.Id);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

BibliotecaCacau/Controllers/UsuarioController.cs
using BibliotecaBookHub.Models.Contracts.Services;
using BibliotecaBookHub.Models.DTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BibliotecaBookHub.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioService _usuarioService;

        public UsuarioController(IUsuarioService usuarioService)
        {
            _usuarioService = usuarioService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string login, string senha)
        {
            try
            {
                UsuarioDTO usuario = new UsuarioDTO { Login = login, Senha = senha };
                UsuarioDTO resultado =  _usuarioService.EfetuarLogin(usuario);

                if(resultado != null)
                {
                    HttpContext.Session.SetString("_UserId", resultado.Id.ToString());
                    HttpContext.Session.SetString("_Login", resultado.Login);

                    TempData["loginError"] = false;

                    return Redirect("/Emprestimo/Consulta");
                } else
                {
                    TempData["loginError"] = true;

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("_UserId");
            HttpContext.Session.Remove("_Login");

            TempData["loginError"] = false;

            return Redirect("/Home");
        }
    }
}

BibliotecaCacau/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Mvc;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca BookHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            string login = Context.Session.GetString("_Login");
                            if (login != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="List">Livros</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="List">Clientes</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimo" asp-action="Consulta">Empréstimo</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark">Usuário: @login</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-white btn btn-danger" asp-area="" asp-controller="Usuario" asp-action="Logout">Logout</a>
                                </li>
                            }

                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Login</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Biblioteca BookHub
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>